# Node as the parent image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install any needed packages including 'serve'
RUN npm install

# Bundle app source inside the Docker image
COPY . .

# Build the React application
RUN npm run build

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NODE_ENV production

# Run the app using 'serve' when the container launches
CMD ["npm", "start"]
