version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production

  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL= http://backend:5000
